/* Magic terms, shared by the webcam table (captions, the Terms tab) and the digital table (Terms):
   [name, what it means, forms flag ("v": a verb, so "scries"/"scried" match too; "p": a noun with a plural)] */
window.KT_KEYWORDS = [
  ["Deathtouch", "Any amount of damage this deals to a creature is enough to destroy it."],
  ["Defender", "This creature can't attack."],
  ["Double strike", "This creature deals both first-strike and regular combat damage."],
  ["First strike", "This creature deals combat damage before creatures without first strike."],
  ["Enchant", "Says what an Aura can be attached to. It can only be cast targeting, and stay attached to, that kind of object."],
  ["Equip", "Pay the equip cost to attach this Equipment to a creature you control. You can only do this when you could cast a sorcery.", "v"],
  ["Flash", "You may cast this spell any time you could cast an instant."],
  ["Flying", "Can't be blocked except by creatures with flying or reach."],
  ["Haste", "This creature can attack and use tap abilities the turn it comes under your control."],
  ["Hexproof", "Can't be the target of spells or abilities your opponents control."],
  ["Indestructible", "Can't be destroyed by damage or by effects that say \"destroy.\" It can still be exiled, sacrificed, or have its toughness reduced to 0."],
  ["Lifelink", "Damage dealt by this source also causes its controller to gain that much life."],
  ["Menace", "Can't be blocked except by two or more creatures."],
  ["Protection", "Can't be damaged, enchanted or equipped, blocked, or targeted by anything with the stated quality."],
  ["Reach", "This creature can block creatures with flying."],
  ["Trample", "When blocked, combat damage beyond what's lethal to the blockers can be dealt to the player, planeswalker, or battle it's attacking."],
  ["Vigilance", "Attacking doesn't cause this creature to tap."],
  ["Ward", "Whenever this becomes the target of a spell or ability an opponent controls, counter it unless that player pays the ward cost."],
  ["Prowess", "Whenever you cast a noncreature spell, this creature gets +1/+1 until end of turn."],
  ["Scry", "Look at that many cards from the top of your library. Put any number on the bottom and the rest back on top in any order.", "v"],
  ["Surveil", "Look at that many cards from the top of your library. Put any number into your graveyard and the rest back on top in any order.", "v"],
  ["Mill", "Put that many cards from the top of a library into its owner's graveyard.", "v"],
  ["Proliferate", "Choose any number of permanents and/or players, then give each another counter of each kind already there.", "v"],
  ["Investigate", "Create a Clue token.", "v"],
  ["Treasure", "An artifact token with \"{T}, Sacrifice this: Add one mana of any color.\"", "p"],
  ["Food", "An artifact token with \"{2}, {T}, Sacrifice this: You gain 3 life.\"", "p"],
  ["Clue", "An artifact token with \"{2}, Sacrifice this: Draw a card.\"", "p"],
  ["Cascade", "When you cast this spell, exile cards from the top of your library until you exile a nonland card with lower mana value. You may cast it without paying its mana cost. Put the rest on the bottom in a random order.", "v"],
  ["Convoke", "Your creatures can help cast this spell. Each creature you tap while casting it pays for {1} or one mana of that creature's color."],
  ["Cycling", "Pay the cycling cost and discard this card: draw a card."],
  ["Flashback", "You may cast this card from your graveyard for its flashback cost. Then exile it."],
  ["Kicker", "You may pay an additional cost as you cast this spell for an extra effect.", "v"],
  ["Landfall", "An ability word for abilities that trigger whenever a land enters the battlefield under your control."],
  ["Storm", "When you cast this spell, copy it for each spell cast before it this turn."],
  ["Affinity", "This spell costs {1} less to cast for each of the named thing you control."],
  ["Annihilator", "Whenever this creature attacks, the defending player sacrifices that many permanents."],
  ["Infect", "Deals damage to creatures as -1/-1 counters and to players as poison counters."],
  ["Toxic", "Players dealt combat damage by this creature also get that many poison counters."],
  ["Wither", "Deals damage to creatures as -1/-1 counters."],
  ["Persist", "When this creature dies, if it had no -1/-1 counters on it, return it to the battlefield with a -1/-1 counter on it."],
  ["Undying", "When this creature dies, if it had no +1/+1 counters on it, return it to the battlefield with a +1/+1 counter on it."],
  ["Evoke", "You may cast this spell for its evoke cost. If you do, it's sacrificed when it enters.", "v"],
  ["Ninjutsu", "Pay the ninjutsu cost and return an unblocked attacker you control to hand: put this card onto the battlefield tapped and attacking."],
  ["Partner", "You can have two commanders if both have partner."],
  ["Exalted", "Whenever a creature you control attacks alone, it gets +1/+1 until end of turn for each instance of exalted among permanents you control."],
  ["Myriad", "Whenever this attacks, for each other opponent, you may create a token copy tapped and attacking that player or their planeswalker. Exile the tokens at end of combat."],
  ["Split second", "While this spell is on the stack, players can't cast spells or activate abilities that aren't mana abilities."],
  ["Crew", "Tap any number of untapped creatures you control with total power at least the crew number: this Vehicle becomes an artifact creature until end of turn.", "v"],
  ["Delve", "Each card you exile from your graveyard while casting this spell pays for {1}."],
  ["Dredge", "If you would draw a card, you may instead mill that many cards and return this card from your graveyard to your hand.", "v"],
  ["Escape", "You may cast this card from your graveyard for its escape cost, which includes exiling other cards from your graveyard."],
  ["Foretell", "During your turn, pay {2} and exile this card face down. Cast it on a later turn for its foretell cost.", "v"],
  ["Connive", "Draw a card, then discard a card. If you discarded a nonland card, put a +1/+1 counter on this creature.", "v"],
  ["Explore", "Reveal the top card of your library. If it's a land, put it in your hand. Otherwise, put a +1/+1 counter on this creature, then you may put that card into your graveyard.", "v"],
  ["Amass", "Put that many +1/+1 counters on an Army you control. If you don't control one, create a 0/0 Army creature token first.", "v"],
  ["Extort", "Whenever you cast a spell, you may pay {W/B}. If you do, each opponent loses 1 life and you gain that much life."],
  ["Morph", "You may cast this face down as a 2/2 creature for {3}. Turn it face up any time for its morph cost."],
  ["Disguise", "You may cast this face down as a 2/2 creature with ward {2} for {3}. Turn it face up any time for its disguise cost."],
  ["Changeling", "This object is every creature type."],
  ["Buyback", "You may pay an additional buyback cost as you cast this. If you do, put it into your hand as it resolves."],
  ["Devour", "As this enters, you may sacrifice any number of creatures. It enters with that many +1/+1 counters for each creature sacrificed.", "v"],
  ["Echo", "At the beginning of your upkeep, if this came under your control since your last upkeep, sacrifice it unless you pay its echo cost."],
  ["Fabricate", "When this enters, put that many +1/+1 counters on it or create that many 1/1 Servo artifact creature tokens."],
  ["Exploit", "When this creature enters, you may sacrifice a creature.", "v"],
  ["Emerge", "You may cast this by sacrificing a creature and paying the emerge cost, reduced by that creature's mana value."],
  ["Battle cry", "Whenever this creature attacks, each other attacking creature gets +1/+0 until end of turn."],
  ["Bloodthirst", "If an opponent was dealt damage this turn, this creature enters with that many +1/+1 counters."],
  ["Goad", "Until your next turn, the goaded creature attacks each combat if able and attacks a player other than you if able.", "v"],
  ["Suspend", "Exile this from your hand with that many time counters by paying the suspend cost. Remove one each upkeep. When the last is removed, cast it without paying its mana cost.", "v"],
  ["Rebound", "If you cast this from your hand, exile it as it resolves. At your next upkeep, you may cast it from exile without paying its mana cost."],
  ["Unearth", "Pay the unearth cost: return this from your graveyard to the battlefield with haste. Exile it at the next end step or if it would leave the battlefield.", "v"],
  ["Jump-start", "You may cast this from your graveyard by paying its cost and discarding a card. Then exile it."],
  ["Overload", "You may cast this for its overload cost. If you do, change \"target\" in its text to \"each.\"", "v"],
  ["Madness", "If you discard this card, you may cast it for its madness cost instead of putting it into your graveyard."],
  ["Mutate", "Cast this for its mutate cost targeting a non-Human creature you own. Merge it on top or underneath. The merged creature has all their abilities.", "v"],
  ["Blitz", "Cast this for its blitz cost. It gains haste and \"When this dies, draw a card,\" and is sacrificed at the next end step."],
  ["Casualty", "As you cast this, you may sacrifice a creature with at least that much power. If you do, copy the spell."],
  ["Training", "Whenever this creature attacks with another creature with greater power, put a +1/+1 counter on it."],
  ["Hideaway", "When this enters, look at that many cards from the top of your library, exile one face down, and put the rest on the bottom. You may play it later without paying its mana cost when a condition is met."],
  ["Commander tax", "Casting your commander from the command zone costs {2} more for each previous time you've cast it from there this game."],
  ["Mana value", "The total amount of mana in a card's mana cost. X counts as 0 except while the spell is on the stack."],
  ["Monarch", "The monarch draws an extra card at the beginning of their end step. Deal combat damage to the monarch to become the monarch."],
  ["Initiative", "When you take the initiative and at the beginning of your upkeep, venture into Undercity. Deal combat damage to the player with the initiative to take it."],
  ["Venture into the dungeon", "Move your marker into the first room of a dungeon, or to the next room of the one you're in, and get that room's effect."],
  ["The Ring tempts you", "Choose a creature you control as your Ring-bearer. Your Ring gains its next ability, up to four."],
  ["Energy", "Counters a player can get, shown as {E}, and spend to pay costs.", "p"],
  ["Poison", "A player with ten or more poison counters loses the game."],
  // Game terms people say all the time
  ["Graveyard", "Where cards go when they're destroyed, sacrificed, discarded, countered, or finish resolving. Face up; anyone can look.", "p"],
  ["Exile", "A zone for cards removed from the game. Cards there usually stay there unless something lets you play them or return them.", "v"],
  ["Library", "Your deck during the game. Cards are drawn from the top.", "p"],
  ["Battlefield", "Where permanents are: lands, creatures, artifacts, enchantments, planeswalkers, and battles in play."],
  ["The stack", "Where spells and abilities wait to resolve. The last one added resolves first, and players can respond before each one does."],
  ["Upkeep", "The step after untap at the start of each turn. Upkeep triggers happen here, before the draw.", "p"],
  ["Draw step", "The step where the active player draws a card, after upkeep."],
  ["End step", "The first part of the end of a turn. \"At the beginning of the end step\" triggers happen here."],
  ["Combat damage", "Damage dealt by attacking and blocking creatures during the combat damage step."],
  ["Commander damage", "A player dealt 21 or more combat damage by the same commander over the game loses."],
  ["Sacrifice", "Move a permanent you control to its owner's graveyard. It can't be prevented, and it isn't destroying.", "v"],
  ["Token", "A permanent that isn't a card, made by an effect. It stops existing when it leaves the battlefield.", "p"],
  ["Planeswalker", "A permanent type with loyalty. You can activate one of its loyalty abilities once per turn, when you could cast a sorcery.", "p"],
  ["Loyalty", "Counters on a planeswalker. Damage to it removes that many; it's put into the graveyard at 0."],
  ["Mulligan", "Shuffle your opening hand back and draw a new one. In Commander your first mulligan is free; after that, put one card on the bottom for each mulligan.", "v"],
  ["Enters the battlefield", "Triggers when a permanent comes into play (often shortened to ETB)."],
  ["ETB", "Short for \"enters the battlefield\": abilities that trigger when a permanent comes into play."],
  ["Summoning sickness", "A creature can't attack or use {T} abilities unless you've controlled it continuously since your most recent turn began."],
  ["Priority", "The right to cast a spell or activate an ability. Players pass priority back and forth; when all pass in a row, the top of the stack resolves."],
  ["Instant", "A spell you can cast any time you have priority, even during other players' turns.", "p"],
  ["Sorcery", "A spell you can cast only during your main phase when the stack is empty.", "p"],
  ["Legendary", "You can control only one permanent with the same name that's legendary. If you get a second, choose one and put the other into the graveyard."],
  ["Colorless", "Having no color. Colorless mana, shown as {C}, can only be made by certain sources."],
  ["Main phase", "The phases before and after combat where you can play a land and cast sorceries and permanents.", "p"],
  ["Untap", "Turn a tapped permanent upright. Everything you control untaps at the start of your turn.", "v"],
  ["Triggered ability", "An ability that starts with \"when,\" \"whenever,\" or \"at.\" It goes on the stack when its event happens.", "p"],
  ["Activated ability", "An ability written as \"cost: effect.\" You can activate it any time you could cast an instant, unless it says otherwise.", "p"],
  ["Counterspell", "A spell that counters another spell, so it has no effect and goes to the graveyard.", "p"],
  ["Board wipe", "A spell that destroys or removes all or most creatures (or other permanents), like Wrath of God.", "p"],
  ["Ramp", "Getting extra mana early, like extra lands or mana rocks, so you can cast big spells sooner."],
  ["Tutor", "Search your library for a card. Named after Demonic Tutor.", "v"],
  ["Mana rock", "An artifact that makes mana, like Sol Ring or Arcane Signet.", "p"],
  ["Mana dork", "A creature that makes mana, like Llanowar Elves or Birds of Paradise.", "p"],
  ["Day and night", "If it's day and the active player casts no spells during their turn, it becomes night next turn. If it's night and a player casts two or more spells in a turn, it becomes day next turn."]
];
